[project]
name = "personal-blog"
version = "0.1.0"
description = "Personal blog"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "django-environ>=0.12.0",
    "whitenoise>=6.9.0",
]
